apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dt-statestore
  namespace: huangs
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: ""
    - name: actorStateStore
      value: "true"
  # - name: enableTLS
  #   value: <bool> # Optional. Allowed: true, false.
  # - name: maxRetries
  #   value: # Optional
  # - name: maxRetryBackoff
  #   value: # Optional
  # - name: failover
  #   value: <bool> # Optional. Allowed: true, false.
  # - name: sentinelMasterName
  #   value: <string> # Optional
  # - name: redeliverInterval
  #   value: # Optional
  # - name: processingTimeout
  #   value: # Optional
  # - name: redisType
  #   value: # Optional
  # - name: redisDB
  #   value: # Optional
  # - name: redisMaxRetries
  #   value: # Optional
  # - name: redisMinRetryInterval
  #   value: # Optional
  # - name: redisMaxRetryInterval
  #   value: # Optional
  # - name: dialTimeout
  #   value: # Optional
  # - name: readTimeout
  #   value: # Optional
  # - name: writeTimeout
  #   value: # Optional
  # - name: poolSize
  #   value: # Optional
  # - name: poolTimeout
  #   value: # Optional
  # - name: maxConnAge
  #   value: # Optional
  # - name: minIdleConns
  #   value: # Optional
  # - name: idleCheckFrequency
  #   value: # Optional
  # - name: idleTimeout
  #   value: # Optional
  # - name: ttlInSeconds
  #   value: <int> # Optional
  # - name: queryIndexes
  #   value: <string> # Optional
