apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: gold-pubsub
  namespace: gold
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      value: "amqp://dapr:123456@rabbitmq:5672"
    - name: username
      value: dapr
    - name: password
      value: "123456"
    - name: durable
      value: "false"
    - name: deletedWhenUnused
      value: "false"
    - name: autoAck
      value: "false"
    - name: reconnectWait
      value: "0"
    - name: concurrencyMode
      value: parallel